### ISSUE TITLE
About MAG-Scholar Graph dataset

### ISSUE THREAD

**Issue by flyingtango** [TUM-DAML/pprgo_pytorch#3]
Thanks for your work. May I know how to download the processed MAG-Scholar Graph dataset? Or provide the processing scripts so that we can generate the dataset by myself.

**Comment by abojchevski** [comment]
You can find it here: https://figshare.com/articles/dataset/mag_scholar/12696653

**Comment by flyingtango** [comment]
Thank you for the quick reply! This provided all I need so that I can follow your work.

**Comment by flyingtango** [comment]
May I also request access to the exact same raw snapshot that you used? Since I want to make an unstandardized version. Thanks！

**Comment by abojchevski** [comment]
By raw snapshot do you mean the actual raw data before any preprocessing? Or the graph that we construct from the raw data before cleaning it up?

**Comment by flyingtango** [comment]
Both are ok. The raw MAG data mentioned in the _readme.md_ file or the adj and attr matrices before "Filter and Standardize" process in the _meg_preprocessing.ipynb_ .

**Comment by cenyk1230** [comment]
Hi @abojchevski ,

Thanks for the great work!
Is there any chance for us to get the raw texts of MAG-Scholar dataset?

**Comment by abojchevski** [comment]
Unfortunately, we cannot provide the raw texts.
