### ISSUE TITLE
About the experiments on Reddit

### ISSUE THREAD

**Issue by wzfhaha** [TUM-DAML/pprgo_pytorch#4]
Dear Author,
    I wonder the details of the experiments on Reddit, as the original setting of Reddit is full-supervised and inductive. How do you split the datasets in your paper? Do you follow the inductive setting (test nodes are not included in training)?

**Comment by gasteigerjo** [comment]
We use a transductive setting with a small, randomly sampled training set in all of our experiments, including Reddit. Note that we sample uniformly, so we could have 50 nodes from one class and 0 nodes from another class. From the paper:

> To best align with real use cases we only use `20·number of classes` uniformly sampled (non-stratified) training nodes.
